[server]
JwtSecret=''
JwtIssue='wxcomponent'
JwtExpireTime=43200
AesKey=''

[wxapi]
UseCloudBaseAccessToken=true
UseComponentAccessToken=false
UseHttps=true

[comm]
Version='2.1.0'

[custom]
MYSQL_USERNAME="admin"          #数据库用户名
MYSQL_PASSWORD="Aa123456"       #数据库密码
MYSQL_ADDRESS="127.0.0.1:3306"  #数据库地址
WX_APPID="wx################"   #微信APPID
FRONTEND_PORT=":80"             #前端访问入口地址
BACKEND_PORT="127.0.0.1:8081"   #内部api端口
ADMIN_USERNAME="admin"          #登陆用户名
ADMIN_PASSWORD="Aa123456"       #登陆密码
